export const GET_USER = 'GET_USER'
export const SET_USER = 'SET_USER'
export const GET_ROOM = 'GET_ROOM'
export const GET_SETTINS = 'GET_SETTINS'
export const SET_ROOM = 'SET_ROOM'
export const CHANGE_USER = 'CHANGE_USER'
export const GET_USERS = 'GET_USERS'
export const LEAVE_ROOM = 'LEAVE_ROOM'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const SET_SETTINGS = 'SET_SETTINGS'

// export const GET_USER = 'GET_USER'
// export const GET_USER = 'GET_USER'
// export const GET_USER = 'GET_USER'
// export const GET_USER = 'GET_USER'
// export const GET_USER = 'GET_USER'
